name: Zappa CI/CD → AWS Lambda

on:
  push:
    branches: [pipeline]

env:
  AWS_REGION: ap-south-1

jobs:
  deploy:
    name: Deploy Flask App to Lambda via Zappa
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Zappa (if first deploy)
        if: ${{ github.event.head_commit.message == 'Init Zappa' }}
        run: |
          zappa init --yes

      - name: Deploy or Update Lambda via Zappa
        run: |
          # If the Lambda function does not yet exist, this does the first deploy.
          # Otherwise, it updates the existing deployment.
          zappa deploy dev || zappa update dev
