name: CI/CD → EC2 Rolling Update via ASG

on:
  push:
    branches: [pipeline]

env:
  AWS_REGION: ap-south-1
  ECR_REPO: 494077377285.dkr.ecr.ap-south-1.amazonaws.com/flask/app
  LT_ID: lt-010501669f893b576
  ASG_NAME: flask-app-asg

jobs:
  build_and_push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    environment: prod
    outputs:
      new-image-tag: ${{ steps.tag.outputs.new_image_tag }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: ${{ env.AWS_REGION }}

      - name: Determine image tag (short SHA)
        id: tag
        run: |
          NEW_TAG=$(echo $GITHUB_SHA | head -c7)
          echo "new_image_tag=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "new_image_tag=$NEW_TAG" >> $GITHUB_ENV

      - name: Build, tag, and push to ECR
        run: |
          docker build -t $ECR_REPO:$new_image_tag .
          docker push $ECR_REPO:$new_image_tag
